# Generated by Django 5.0.6 on 2024-09-02 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_name_templatemodel_template_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.TextField()),
                ('root_cause', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='evidence/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.actionplan')),
            ],
        ),
        migrations.CreateModel(
            name='RFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=50)),
                ('process_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actionplan',
            name='rfa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rfa'),
        ),
    ]
