# Generated by Django 5.0.6 on 2024-09-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_actionplan_evidence_rfa_actionplan_rfa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='action_plan',
        ),
        migrations.RemoveField(
            model_name='rfa',
            name='process_owner',
        ),
        migrations.DeleteModel(
            name='ActionPlan',
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
        migrations.DeleteModel(
            name='RFA',
        ),
    ]
