# Generated by Django 5.0.6 on 2024-09-02 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_evidence_action_plan_remove_rfa_process_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('department', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('non_conformity_type', models.CharField(choices=[('IQA', 'IQA-Related'), ('Supplier', 'Supplier-Related'), ('3rd_Party', '3rd Party Audit Related'), ('Customer', 'Customer Satisfaction Related'), ('Process', 'Process/Procedural-related'), ('HRD', 'HRD-Related'), ('KPI', 'Relates to KPI/Quality Objective Review'), ('Other', 'Others')], max_length=20)),
                ('iso_clause_reference', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor')], max_length=10)),
                ('immediate_action', models.TextField()),
                ('root_cause_analysis', models.TextField(blank=True, null=True)),
                ('corrective_action_plan', models.TextField(blank=True, null=True)),
                ('responsible_officer', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('close_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Open', max_length=50)),
                ('originator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
