# Generated by Django 5.0.6 on 2024-09-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userprofile_is_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_first_login',
        ),
    ]
