# Generated by Django 5.0.6 on 2024-09-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_guideline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guideline',
        ),
    ]
