# Generated by Django 5.0.6 on 2024-09-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_userprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
    ]
